#include "fixtures.h"

#include <QCommandLineParser>
#include <QCoreApplication>
#include <QFile>
#include <QFileInfo>
#include <QGuiApplication>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>

#include <cstdio>

using namespace pimio::fixtures;

int main(int argc, char *argv[])
{
    // QImage encoding needs the GUI module but no display.
    qputenv("QT_QPA_PLATFORM", "offscreen");
    QGuiApplication application(argc, argv);
    QCoreApplication::setApplicationName(QStringLiteral("pimio-fixture-generator"));

    QCommandLineParser parser;
    parser.setApplicationDescription(
            QStringLiteral("Regenerates the pimio test fixture corpus and its manifest."));
    parser.addHelpOption();
    QCommandLineOption outputOption({QStringLiteral("o"), QStringLiteral("output")},
                                    QStringLiteral("Fixture directory to write."),
                                    QStringLiteral("directory"));
    parser.addOption(outputOption);
    parser.process(application);

    if (!parser.isSet(outputOption)) {
        std::fprintf(stderr, "An output directory is required.\n");
        return 2;
    }

    const QDir outputDir(parser.value(outputOption));
    const QList<Fixture> fixtures = buildFixtures();

    QJsonArray entries;
    for (const Fixture &fixture : fixtures) {
        const QString absolutePath = outputDir.absoluteFilePath(fixture.path);
        if (!QDir().mkpath(QFileInfo(absolutePath).absolutePath())) {
            std::fprintf(stderr, "Cannot create directory for %s\n",
                         qPrintable(fixture.path));
            return 1;
        }

        QFile file(absolutePath);
        if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
            std::fprintf(stderr, "Cannot write %s\n", qPrintable(absolutePath));
            return 1;
        }
        if (!fixture.contents.isEmpty()
            && file.write(fixture.contents) != fixture.contents.size()) {
            std::fprintf(stderr, "Short write for %s\n", qPrintable(absolutePath));
            return 1;
        }
        file.close();

        QJsonObject entry;
        entry.insert(QStringLiteral("path"), fixture.path);
        entry.insert(QStringLiteral("sizeBytes"), fixture.contents.size());
        entry.insert(QStringLiteral("sha256"), sha256Of(fixture.contents));
        entry.insert(QStringLiteral("provenance"),
                     QStringLiteral("Generated by tools/fixture_generator. Owned by the pimio "
                                    "project; no third-party media is included."));
        entry.insert(QStringLiteral("covers"), fixture.covers);
        if (!fixture.notes.isEmpty()) {
            entry.insert(QStringLiteral("notes"), fixture.notes);
        }
        entries.append(entry);
    }
    if (!appendExternalFixtureEntries(outputDir, &entries)) {
        return 1;
    }

    QJsonObject manifest;
    manifest.insert(QStringLiteral("schemaVersion"), 1);
    manifest.insert(QStringLiteral("generator"), QStringLiteral("tools/fixture_generator"));
    manifest.insert(QStringLiteral("generatedWithQtVersion"),
                    QString::fromLatin1(qVersion()));
    manifest.insert(QStringLiteral("fixtures"), entries);

    QFile manifestFile(outputDir.absoluteFilePath(QStringLiteral("manifest.json")));
    if (!manifestFile.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
        std::fprintf(stderr, "Cannot write the manifest.\n");
        return 1;
    }
    manifestFile.write(QJsonDocument(manifest).toJson(QJsonDocument::Indented));
    manifestFile.close();

    std::printf("Wrote %lld fixtures to %s\n", static_cast<long long>(fixtures.size()),
                qPrintable(outputDir.absolutePath()));
    return 0;
}
